package com.seasonfif.jetpack.net

class NetConstants {

    companion object{
        const val BASE_URL = "https://www.wanandroid.com/"

        const val LOCAL = """
            {
    "curPage": 1,
    "datas": [
        {
            "apkLink": "",
            "audit": 1,
            "author": "jzh1996",
            "canEdit": false,
            "chapterId": 294,
            "chapterName": "完整项目",
            "collect": false,
            "courseId": 13,
            "desc": "采用 Kotlin 语言编写，结合 MVVM + 协程 + Retrofit + Glide + JetPack部分功能 等架构设计的项目，项目代码结构清晰，如有任何疑问和建议请提 Issues 或联系 qq： 1510931535 ，项目会持续迭代维护。",
            "descMd": "",
            "envelopePic": "https://www.wanandroid.com/blogimgs/31e0b08e-3a25-4d0c-9e6e-bd6a9e32646f.png",
            "fresh": false,
            "host": "",
            "id": 17002,
            "link": "https://www.wanandroid.com/blog/show/2918",
            "niceDate": "2天前",
            "niceShareDate": "2天前",
            "origin": "",
            "prefix": "",
            "projectLink": "https://github.com/jzh1996/mvvm",
            "publishTime": 1611243091000,
            "realSuperChapterId": 293,
            "selfVisible": 0,
            "shareDate": 1611243091000,
            "shareUser": "",
            "superChapterId": 294,
            "superChapterName": "开源项目主Tab",
            "tags": [
                {
                    "name": "项目",
                    "url": "/project/list/1?cid=294"
                }
            ],
            "title": "基本玩Android API的kotlin版app",
            "type": 0,
            "userId": -1,
            "visible": 1,
            "zan": 0
        },
        {
            "apkLink": "",
            "audit": 1,
            "author": "Hankkin",
            "canEdit": false,
            "chapterId": 294,
            "chapterName": "完整项目",
            "collect": false,
            "courseId": 13,
            "desc": "JetpackNote 是一款基于谷歌官方组件Jetpack开发的笔记项目，项目中包含了对各大组件的源码分析、Demo使用：Navigation、Lifecycles、Paging、LiveData、ViewModel等...",
            "descMd": "",
            "envelopePic": "https://www.wanandroid.com/blogimgs/d9d0967f-d6b9-4abe-ae1f-054a1030c4a6.png",
            "fresh": false,
            "host": "",
            "id": 16955,
            "link": "https://www.wanandroid.com/blog/show/2909",
            "niceDate": "2021-01-19 01:03",
            "niceShareDate": "2021-01-19 01:03",
            "origin": "",
            "prefix": "",
            "projectLink": "https://github.com/Hankkin/JetPack_Note",
            "publishTime": 1610989434000,
            "realSuperChapterId": 293,
            "selfVisible": 0,
            "shareDate": 1610989434000,
            "shareUser": "",
            "superChapterId": 294,
            "superChapterName": "开源项目主Tab",
            "tags": [
                {
                    "name": "项目",
                    "url": "/project/list/1?cid=294"
                }
            ],
            "title": "JetpackNote---基于Jetpack的学习笔记APP",
            "type": 0,
            "userId": -1,
            "visible": 1,
            "zan": 0
        },
        {
            "apkLink": "",
            "audit": 1,
            "author": "yzbkaka",
            "canEdit": false,
            "chapterId": 294,
            "chapterName": "完整项目",
            "collect": false,
            "courseId": 13,
            "desc": "一款基于Android的时间管理APP，主要采用Litepal框架进行数据库存储。页面简洁，功能实用。注释详尽，尽力符合规范。比较适合新手Android开发者进行练手。\r\n\r\n",
            "descMd": "",
            "envelopePic": "https://www.wanandroid.com/blogimgs/54602cb2-aa6a-4d59-a546-1282454d9439.png",
            "fresh": false,
            "host": "",
            "id": 16954,
            "link": "https://www.wanandroid.com/blog/show/2908",
            "niceDate": "2021-01-19 01:02",
            "niceShareDate": "2021-01-19 01:02",
            "origin": "",
            "prefix": "",
            "projectLink": "https://github.com/yzbkaka/Schedule",
            "publishTime": 1610989321000,
            "realSuperChapterId": 293,
            "selfVisible": 0,
            "shareDate": 1610989321000,
            "shareUser": "",
            "superChapterId": 294,
            "superChapterName": "开源项目主Tab",
            "tags": [
                {
                    "name": "项目",
                    "url": "/project/list/1?cid=294"
                }
            ],
            "title": "[新手向] 时间管理App&mdash;&mdash;Schedule",
            "type": 0,
            "userId": -1,
            "visible": 1,
            "zan": 0
        },
        {
            "apkLink": "",
            "audit": 1,
            "author": "390057892",
            "canEdit": false,
            "chapterId": 294,
            "chapterName": "完整项目",
            "collect": false,
            "courseId": 13,
            "desc": "一款使用Kt编写的小说阅读器,支持追书、看书。拥有语音朗读、仿真翻页、插画、国际化、黑夜模式等功能，适配了安卓9.0,使用AndroidX控件,对刘海屏等异形屏幕有了很好的支持",
            "descMd": "",
            "envelopePic": "https://www.wanandroid.com/blogimgs/0c2f76e3-0af7-4dae-a4d8-98173d24512c.png",
            "fresh": false,
            "host": "",
            "id": 16908,
            "link": "https://www.wanandroid.com/blog/show/2903",
            "niceDate": "2021-01-14 23:48",
            "niceShareDate": "2021-01-14 23:48",
            "origin": "",
            "prefix": "",
            "projectLink": "https://github.com/390057892/reader",
            "publishTime": 1610639337000,
            "realSuperChapterId": 293,
            "selfVisible": 0,
            "shareDate": 1610639337000,
            "shareUser": "",
            "superChapterId": 294,
            "superChapterName": "开源项目主Tab",
            "tags": [
                {
                    "name": "项目",
                    "url": "/project/list/1?cid=294"
                }
            ],
            "title": "&quot;轻之阅读&quot;网络小说阅读器 Reader",
            "type": 0,
            "userId": -1,
            "visible": 1,
            "zan": 0
        },
        {
            "apkLink": "",
            "audit": 1,
            "author": "KKaKa",
            "canEdit": false,
            "chapterId": 294,
            "chapterName": "完整项目",
            "collect": false,
            "courseId": 13,
            "desc": "Kotlin写的MVVM + LiveData + RxJava + okHttp + Retrofit + Room +Glide的玩Android客户端",
            "descMd": "",
            "envelopePic": "https://www.wanandroid.com/blogimgs/5110fb23-ce6b-4bd0-84c5-66a0e19b056a.png",
            "fresh": false,
            "host": "",
            "id": 16903,
            "link": "https://www.wanandroid.com/blog/show/2902",
            "niceDate": "2021-01-14 23:42",
            "niceShareDate": "2021-01-14 23:42",
            "origin": "",
            "prefix": "",
            "projectLink": "https://github.com/KKaKa/WanAndroid",
            "publishTime": 1610638942000,
            "realSuperChapterId": 293,
            "selfVisible": 0,
            "shareDate": 1610638942000,
            "shareUser": "",
            "superChapterId": 294,
            "superChapterName": "开源项目主Tab",
            "tags": [
                {
                    "name": "项目",
                    "url": "/project/list/1?cid=294"
                }
            ],
            "title": "Kotlin+MVVM的客户端",
            "type": 0,
            "userId": -1,
            "visible": 1,
            "zan": 0
        },
        {
            "apkLink": "",
            "audit": 1,
            "author": "yzbkaka",
            "canEdit": false,
            "chapterId": 294,
            "chapterName": "完整项目",
            "collect": false,
            "courseId": 13,
            "desc": "一款基于MeetMusic的Android本地音乐播放器，具有音乐播放，创建歌单，主题变色，暗色模式以及状态播放通知等功能`，完成度较高，同时代码注释比较详解，比较适合android开发学习。\r\n",
            "descMd": "",
            "envelopePic": "https://www.wanandroid.com/blogimgs/c7a989d6-7c3e-46bd-846f-abc75f0bc2b3.png",
            "fresh": false,
            "host": "",
            "id": 16882,
            "link": "https://www.wanandroid.com/blog/show/2900",
            "niceDate": "2021-01-13 23:51",
            "niceShareDate": "2021-01-13 23:51",
            "origin": "",
            "prefix": "",
            "projectLink": "https://github.com/yzbkaka/kakaMusic",
            "publishTime": 1610553061000,
            "realSuperChapterId": 293,
            "selfVisible": 0,
            "shareDate": 1610553061000,
            "shareUser": "",
            "superChapterId": 294,
            "superChapterName": "开源项目主Tab",
            "tags": [
                {
                    "name": "项目",
                    "url": "/project/list/1?cid=294"
                }
            ],
            "title": "一款酷炫的android本地播放器",
            "type": 0,
            "userId": -1,
            "visible": 1,
            "zan": 0
        },
        {
            "apkLink": "",
            "audit": 1,
            "author": "Mrfzh",
            "canEdit": false,
            "chapterId": 294,
            "chapterName": "完整项目",
            "collect": false,
            "courseId": 13,
            "desc": "个人开发的小说阅读器，支持搜索和阅读网络小说，导入和阅读本地 TXT、本地 EPUB 小说。",
            "descMd": "",
            "envelopePic": "https://www.wanandroid.com/blogimgs/d3c24118-d9db-424d-a8f7-120f75564cf1.png",
            "fresh": false,
            "host": "",
            "id": 16881,
            "link": "https://www.wanandroid.com/blog/show/2899",
            "niceDate": "2021-01-13 23:49",
            "niceShareDate": "2021-01-13 23:49",
            "origin": "",
            "prefix": "",
            "projectLink": "https://github.com/Mrfzh/FReader",
            "publishTime": 1610552980000,
            "realSuperChapterId": 293,
            "selfVisible": 0,
            "shareDate": 1610552980000,
            "shareUser": "",
            "superChapterId": 294,
            "superChapterName": "开源项目主Tab",
            "tags": [
                {
                    "name": "项目",
                    "url": "/project/list/1?cid=294"
                }
            ],
            "title": "FReader 小说阅读器，支持阅读网络、本地 TXT、本地 EPUB 小说",
            "type": 0,
            "userId": -1,
            "visible": 1,
            "zan": 0
        },
        {
            "apkLink": "",
            "audit": 1,
            "author": "LinHuanTanLy",
            "canEdit": false,
            "chapterId": 294,
            "chapterName": "完整项目",
            "collect": false,
            "courseId": 13,
            "desc": "FishRedux完成一个玩安卓客户端",
            "descMd": "",
            "envelopePic": "https://www.wanandroid.com/blogimgs/fc9b4161-2244-40e2-b427-92ee5e6c98f4.png",
            "fresh": false,
            "host": "",
            "id": 16859,
            "link": "https://www.wanandroid.com/blog/show/2894",
            "niceDate": "2021-01-11 22:11",
            "niceShareDate": "2021-01-11 22:11",
            "origin": "",
            "prefix": "",
            "projectLink": "https://github.com/LinHuanTanLy/FishReduxFunAndroid",
            "publishTime": 1610374300000,
            "realSuperChapterId": 293,
            "selfVisible": 0,
            "shareDate": 1610374300000,
            "shareUser": "",
            "superChapterId": 294,
            "superChapterName": "开源项目主Tab",
            "tags": [
                {
                    "name": "项目",
                    "url": "/project/list/1?cid=294"
                }
            ],
            "title": "FishRedux完成一个玩安卓客户端",
            "type": 0,
            "userId": -1,
            "visible": 1,
            "zan": 0
        },
        {
            "apkLink": "",
            "audit": 1,
            "author": "jenly1314",
            "canEdit": false,
            "chapterId": 294,
            "chapterName": "完整项目",
            "collect": false,
            "courseId": 13,
            "desc": " SplitEditText 一个灵活的分割编辑框。常常应用于验证码输入 、密码输入等场景。",
            "descMd": "",
            "envelopePic": "https://www.wanandroid.com/blogimgs/821d0065-3cd5-4be7-a43c-dc7349b7513b.png",
            "fresh": false,
            "host": "",
            "id": 16805,
            "link": "https://www.wanandroid.com/blog/show/2889",
            "niceDate": "2021-01-08 00:22",
            "niceShareDate": "2021-01-08 00:22",
            "origin": "",
            "prefix": "",
            "projectLink": "https://github.com/jenly1314/SplitEditText",
            "publishTime": 1610036520000,
            "realSuperChapterId": 293,
            "selfVisible": 0,
            "shareDate": 1610036520000,
            "shareUser": "",
            "superChapterId": 294,
            "superChapterName": "开源项目主Tab",
            "tags": [
                {
                    "name": "项目",
                    "url": "/project/list/1?cid=294"
                }
            ],
            "title": " SplitEditText 一个灵活的分割编辑框。常常应用于验证码输入 、密码输入等场景。",
            "type": 0,
            "userId": -1,
            "visible": 1,
            "zan": 0
        },
        {
            "apkLink": "",
            "audit": 1,
            "author": "chenweide",
            "canEdit": false,
            "chapterId": 294,
            "chapterName": "完整项目",
            "collect": false,
            "courseId": 13,
            "desc": "一款浏览Android学习文章的App。\r\n该项目主要架构为Material Design+MVP+Retrofit2+Rxjava2，基于鸿洋大神提供的玩Android的开放API构建而成。",
            "descMd": "",
            "envelopePic": "https://www.wanandroid.com/resources/image/pc/default_project_img.jpg",
            "fresh": false,
            "host": "",
            "id": 16770,
            "link": "https://www.wanandroid.com/blog/show/2887",
            "niceDate": "2021-01-05 23:06",
            "niceShareDate": "2021-01-05 23:06",
            "origin": "",
            "prefix": "",
            "projectLink": "https://github.com/chenweide/wanAndroid",
            "publishTime": 1609859194000,
            "realSuperChapterId": 293,
            "selfVisible": 0,
            "shareDate": 1609859194000,
            "shareUser": "",
            "superChapterId": 294,
            "superChapterName": "开源项目主Tab",
            "tags": [
                {
                    "name": "项目",
                    "url": "/project/list/1?cid=294"
                }
            ],
            "title": "Material Design+MVP+Retrofit2+Rxjava2（灰常简洁的WanAndroid客户端）",
            "type": 0,
            "userId": -1,
            "visible": 1,
            "zan": 0
        },
        {
            "apkLink": "",
            "audit": 1,
            "author": "1170762202",
            "canEdit": false,
            "chapterId": 294,
            "chapterName": "完整项目",
            "collect": false,
            "courseId": 13,
            "desc": "组件化 + Arouter + Jetpack + Rxjava + Retrofit + AOP等框架",
            "descMd": "",
            "envelopePic": "https://www.wanandroid.com/blogimgs/e3ee00d6-3332-4b86-abf1-2a6ff0a78ae6.png",
            "fresh": false,
            "host": "",
            "id": 16769,
            "link": "https://www.wanandroid.com/blog/show/2886",
            "niceDate": "2021-01-05 23:05",
            "niceShareDate": "2021-01-05 23:05",
            "origin": "",
            "prefix": "",
            "projectLink": "https://github.com/1170762202/WanAndroid",
            "publishTime": 1609859119000,
            "realSuperChapterId": 293,
            "selfVisible": 0,
            "shareDate": 1609859119000,
            "shareUser": "",
            "superChapterId": 294,
            "superChapterName": "开源项目主Tab",
            "tags": [
                {
                    "name": "项目",
                    "url": "/project/list/1?cid=294"
                }
            ],
            "title": "你们要的Android组件化来了，module单独编译运行",
            "type": 0,
            "userId": -1,
            "visible": 1,
            "zan": 0
        },
        {
            "apkLink": "",
            "audit": 1,
            "author": "Yuongzw",
            "canEdit": false,
            "chapterId": 294,
            "chapterName": "完整项目",
            "collect": false,
            "courseId": 13,
            "desc": "基于 wanandroid.com 开发的 MVVM+ Retrofit + RxJava2 + kotlin语言开发的 Android APP",
            "descMd": "",
            "envelopePic": "https://www.wanandroid.com/blogimgs/5e6a3422-93b8-4e3d-8f92-8c1784c62b1c.png",
            "fresh": false,
            "host": "",
            "id": 16748,
            "link": "https://www.wanandroid.com/blog/show/2883",
            "niceDate": "2021-01-05 00:22",
            "niceShareDate": "2021-01-05 00:22",
            "origin": "",
            "prefix": "",
            "projectLink": "https://github.com/Yuongzw/WanAndroidKotlin/",
            "publishTime": 1609777338000,
            "realSuperChapterId": 293,
            "selfVisible": 0,
            "shareDate": 1609777338000,
            "shareUser": "",
            "superChapterId": 294,
            "superChapterName": "开源项目主Tab",
            "tags": [
                {
                    "name": "项目",
                    "url": "/project/list/1?cid=294"
                }
            ],
            "title": "基于MVVM的Wan Android APP -- Kotlin版本",
            "type": 0,
            "userId": -1,
            "visible": 1,
            "zan": 0
        },
        {
            "apkLink": "",
            "audit": 1,
            "author": "MikaelZero",
            "canEdit": false,
            "chapterId": 294,
            "chapterName": "完整项目",
            "collect": false,
            "courseId": 13,
            "desc": "flutter开发，支持pixiv基本功能，多语言，暗黑模式，大陆用户直连，支持非会员热度搜索",
            "descMd": "",
            "envelopePic": "https://www.wanandroid.com/blogimgs/2218b5df-46bc-4f5e-b667-888ccc7ee135.png",
            "fresh": false,
            "host": "",
            "id": 16747,
            "link": "https://www.wanandroid.com/blog/show/2882",
            "niceDate": "2021-01-05 00:15",
            "niceShareDate": "2021-01-05 00:15",
            "origin": "",
            "prefix": "",
            "projectLink": "https://github.com/MikaelZero/Piko",
            "publishTime": 1609776901000,
            "realSuperChapterId": 293,
            "selfVisible": 0,
            "shareDate": 1609776901000,
            "shareUser": "",
            "superChapterId": 294,
            "superChapterName": "开源项目主Tab",
            "tags": [
                {
                    "name": "项目",
                    "url": "/project/list/1?cid=294"
                }
            ],
            "title": "Piko(Pixiv第三方flutter客户端)",
            "type": 0,
            "userId": -1,
            "visible": 1,
            "zan": 0
        },
        {
            "apkLink": "",
            "audit": 1,
            "author": "fluttercandies",
            "canEdit": false,
            "chapterId": 294,
            "chapterName": "完整项目",
            "collect": false,
            "courseId": 13,
            "desc": "wechat_flutter是flutter版微信，目前已实现即时通讯基本功能，支持安卓和IOS，具体下载体验。",
            "descMd": "",
            "envelopePic": "https://www.wanandroid.com/blogimgs/8f49deef-c65e-4d3c-8675-48a5e92c07f2.png",
            "fresh": false,
            "host": "",
            "id": 16752,
            "link": "https://www.wanandroid.com/blog/show/2885",
            "niceDate": "2021-01-05 00:11",
            "niceShareDate": "2021-01-05 00:11",
            "origin": "",
            "prefix": "",
            "projectLink": "https://github.com/fluttercandies/wechat_flutter",
            "publishTime": 1609776694000,
            "realSuperChapterId": 293,
            "selfVisible": 0,
            "shareDate": 1609776694000,
            "shareUser": "",
            "superChapterId": 294,
            "superChapterName": "开源项目主Tab",
            "tags": [
                {
                    "name": "项目",
                    "url": "/project/list/1?cid=294"
                }
            ],
            "title": "wechat_flutter Flutter版本微信，一个优秀的Flutter即时通讯IM开源库！",
            "type": 0,
            "userId": -1,
            "visible": 1,
            "zan": 0
        },
        {
            "apkLink": "",
            "audit": 1,
            "author": "bingocode",
            "canEdit": false,
            "chapterId": 294,
            "chapterName": "完整项目",
            "collect": false,
            "courseId": 13,
            "desc": "采用纯Flutter实践的项目，基于北京公交官网数据实现对公交到站信息的查询",
            "descMd": "",
            "envelopePic": "https://www.wanandroid.com/blogimgs/fef2efaa-5581-4e8c-8cd1-05d5898f79db.png",
            "fresh": false,
            "host": "",
            "id": 16719,
            "link": "https://www.wanandroid.com/blog/show/2878",
            "niceDate": "2021-01-03 22:56",
            "niceShareDate": "2021-01-03 22:56",
            "origin": "",
            "prefix": "",
            "projectLink": "https://github.com/bingocode/flutter_bingocode",
            "publishTime": 1609685787000,
            "realSuperChapterId": 293,
            "selfVisible": 0,
            "shareDate": 1609685787000,
            "shareUser": "",
            "superChapterId": 294,
            "superChapterName": "开源项目主Tab",
            "tags": [
                {
                    "name": "项目",
                    "url": "/project/list/1?cid=294"
                }
            ],
            "title": "Flutter实现北京公交实时查询",
            "type": 0,
            "userId": -1,
            "visible": 1,
            "zan": 0
        }
    ],
    "offset": 0,
    "over": false,
    "pageCount": 16,
    "size": 15,
    "total": 239
}
        """
    }
}